apiVersion: v1
kind: Service
metadata:
  name: portal-svc
  labels:
    app: portal
spec:
  type: NodePort
  #  type: ClusterIP
  ports:
    - targetPort: 3000
      port: 80
  selector:
    app: portal
    project: all
    type: frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal-min-ng
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
spec:
  selector:
    matchLabels:
      app: portal
      project: all
      type: frontend
  template:
    metadata:
      name: portal
      labels:
        app: portal
        project: all
        type: frontend
    spec:
      serviceAccountName: portal-min-ng
      containers:
        - name: portal
          image: henryodinaka/portal:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 20Mi
          env:
            - name: PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: cluster-secret
                  key: project-id

          volumeMounts:
            - name: portallog
              mountPath: /portal/src

          livenessProbe:
            exec:
              command:
                - ls
            initialDelaySeconds: 5
            periodSeconds: 5

      volumes:
        - name: portallog
          hostPath:
            path: /var/lib/portal/data
